version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # PostgreSQL
      - POSTGRESQL_NAME=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      # Django
      - SECRET_KEY=glsiw36-skd7q8i0c$i7n=-!yp8-vw7*too07q10i*t15vgx4c
      - DEBUG=1
      # PostgreSQL
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
